language: perl
perl:
  - "5.26"
  - "5.26-shrplib"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.08"

env:
  # Because Text-Chomped uses M::I and needs `use inc:...` to work
  - PERL5LIB=.

install:
  - cpanm ExtUtils::MakeMaker
    # Because EUMM v6.66 doesn't seem to generate the correct MYMETA.json,
    # causing lib::relative not to be loaded as a dependency.  See, e.g.,
    # https://travis-ci.org/cxw42/Class-Tiny-ConstrainedAccessor/jobs/535823908
  - cpanm --with-recommends --verbose --installdeps --notest .
